pipeline {

    agent any

    tools {
        nodejs 'NodeJS-26'
    }

    environment {

        BACKEND_IMAGE = "pranav2329h/cloudvault-backend:latest"
        FRONTEND_IMAGE = "pranav2329h/cloudvault-frontend:latest"

        EC2_HOST = "13.51.204.171"
        EC2_USER = "ubuntu"

        DEPLOY_PATH = "/home/ubuntu/CloudVault/backend"
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Validation') {
            steps {
                dir('backend') {
                    sh '''
                    python3 -m py_compile app.py
                    '''
                }
            }
        }

        stage('Frontend Dependencies') {
            steps {
                dir('frontend') {
                    sh '''
                    npm install
                    '''
                }
            }
        }

        stage('Frontend Build') {
            steps {
                dir('frontend') {
                    sh '''
                    npm run build
                    '''
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('backend') {
                    sh '''
                    docker build -t $BACKEND_IMAGE .
                    '''
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('frontend') {
                    sh '''
                    docker build -t $FRONTEND_IMAGE .
                    '''
                }
            }
        }

        stage('Push Docker Images') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    docker push $BACKEND_IMAGE
                    docker push $FRONTEND_IMAGE

                    docker logout
                    '''

                }

            }

        }

        stage('Deploy to EC2') {

            steps {

                sshagent(credentials: ['ec2-ssh-key']) {

                    sh """
                    ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'

                    set -e

                    cd ${DEPLOY_PATH}

                    docker compose pull

                    docker compose down

                    docker compose up -d

                    docker image prune -af

                    docker compose ps

                    EOF
                    """

                }

            }

        }

        stage('Health Check') {

            steps {

                sh '''

                echo "Waiting for services..."

                sleep 30

                curl -f https://cloudvault-pranav.duckdns.org/health

                curl -f https://cloudvault-pranav.duckdns.org

                '''

            }

        }

    }

    post {

        success {

            echo "======================================="
            echo "Deployment Successful"
            echo "Backend Updated"
            echo "Frontend Updated"
            echo "Docker Images Pushed"
            echo "EC2 Deployment Successful"
            echo "======================================="

        }

        failure {

            echo "======================================="
            echo "Deployment Failed"
            echo "======================================="

        }

        always {

            sh '''

            docker system prune -af || true

            docker builder prune -af || true

            '''

        }

    }

}